//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace GraphLight.Model.LGML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Graph", Namespace="", IsNullable=false)]
    public partial class LgmlGraph {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VertexCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LgmlVertexCategory[] VertexCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EdgeCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LgmlEdgeCategory[] EdgeCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vertex", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LgmlVertex[] Vertex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LgmlEdge[] Edge;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LgmlVertexCategory : LgmlVertexStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlVertexCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlVertex))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class LgmlVertexStyle : LgmlBaseStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LgmlVertexShape Shape;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShapeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Margin;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarginSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LgmlVertexShape {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Ellipse,
        
        /// <remarks/>
        Rectangle,
        
        /// <remarks/>
        Diamond,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlVertexStyle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlVertexCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlVertex))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlEdgeStyle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlEdgeCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlEdge))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class LgmlBaseStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Background;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double FontSize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FontSizeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LgmlFontStyle FontStyle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FontStyleSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LgmlFontWeight FontWeight;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FontWeightSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Foreground;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Stroke;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LgmlStrokeStyle StrokeStyle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StrokeStyleSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double StrokeThickness;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StrokeThicknessSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LgmlTextAlignment TextAlignment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TextAlignmentSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LgmlTextWrapping TextWrapping;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TextWrappingSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LgmlFontStyle {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Italic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LgmlFontWeight {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Bold,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LgmlStrokeStyle {
        
        /// <remarks/>
        Solid,
        
        /// <remarks/>
        Dash,
        
        /// <remarks/>
        DashDot,
        
        /// <remarks/>
        Dot,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LgmlTextAlignment {
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Right,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LgmlTextWrapping {
        
        /// <remarks/>
        NoWrap,
        
        /// <remarks/>
        Wrap,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlEdgeCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LgmlEdge))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class LgmlEdgeStyle : LgmlBaseStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Weight;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LgmlEdgeCategory : LgmlEdgeStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LgmlEdge : LgmlEdgeStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Dst;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Src;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LgmlVertex : LgmlVertexStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label;
    }
}
