<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<UseWPF>true</UseWPF>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<TargetFramework>net8.0-windows</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GraphLight.Layout\GraphLight.Layout.csproj" />
	</ItemGroup>

</Project>